title: Kernel Self-Protection Project
email: linux-hardening@vger.kernel.org
baseurl: ""
url: ""
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
