title: Linux Kernel Self-Protection Project
email: linux-hardening@vger.kernel.org
theme: minima
header_pages:
  - does-not-exist.md
baseurl: ""
url: ""
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
repository: KSPP/kspp.github.io
